# Create a variable for various CMake directories
set(PROJECT_CMAKE_DIR ${PROJECT_SOURCE_DIR}/cmake)
set(CMAKE_CMAKE_DIR ${CMAKE_SOURCE_DIR}/cmake)
set(CODE_TEMPLATE_CMAKE_DIR ${CODE_TEMPLATE_DIR}/cmake)

# Define Third party related directories
if(CMAKE_BUILD_TYPE STREQUAL "")
  set(THIRD_PARTY_ROOT_DIR
    ${THIRD_PARTY_DIR}/${CMAKE_SYSTEM_PROCESSOR}/__default__)
else()
  set(THIRD_PARTY_ROOT_DIR
    ${THIRD_PARTY_DIR}/${CMAKE_SYSTEM_PROCESSOR}/${CMAKE_BUILD_TYPE})
endif()
set(THIRD_PARTY_FIND_DIR ${THIRD_PARTY_ROOT_DIR}${CMAKE_INSTALL_PREFIX})

# Define where to find third party libraries
set(CMAKE_FIND_ROOT_PATH ${THIRD_PARTY_ROOT_DIR})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM both)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY only)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE only)

